# Generated by Django 4.1.13 on 2024-05-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_notificationetudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='vu',
            field=models.BooleanField(default=False),
        ),
    ]
