# Generated by Django 4.1.13 on 2024-05-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
