# Generated by Django 4.1.13 on 2024-05-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('valide_par_admin', models.BooleanField(default=False)),
                ('valide_par_etudiant', models.BooleanField(default=False)),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.conseiller')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.etudiant')),
            ],
            options={
                'db_table': 'Feedbacks',
            },
        ),
    ]
