# Generated by Django 4.1.13 on 2024-05-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEvenement', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Events',
            },
        ),
    ]
