# Generated by Django 5.0.6 on 2024-05-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrateur',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='conseiller',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='conseiller',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='conseiller',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='notificationetudiant',
            name='etudiant',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Visiteur',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Conseiller',
        ),
        migrations.DeleteModel(
            name='Demande',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='NotificationEtudiant',
        ),
    ]
