# Generated by Django 4.1.13 on 2024-05-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0016_delete_administrateur_remove_notification_conseiller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='Conseiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('Instagram', models.CharField(max_length=100)),
                ('Linkedin', models.CharField(max_length=100)),
                ('Gmail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Conseillers',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('CNE', models.CharField(max_length=10)),
                ('CIN', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Etudiants',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEvenement', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Visiteurs',
            },
        ),
        migrations.CreateModel(
            name='NotificationEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.etudiant')),
            ],
            options={
                'db_table': 'Notifications_Etudiant',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vu', models.BooleanField(default=False)),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.conseiller')),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('valide_par_admin', models.BooleanField(default=False)),
                ('valide_par_etudiant', models.BooleanField(default=False)),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.conseiller')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.etudiant')),
            ],
            options={
                'db_table': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('etat', models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée')], default='En attente', max_length=20)),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.conseiller')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.etudiant')),
            ],
            options={
                'db_table': 'Demande',
            },
        ),
    ]
