# Generated by Django 4.1.13 on 2024-05-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
