# Generated by Django 4.1.13 on 2024-05-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_etudiant_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
