# Generated by Django 4.1.13 on 2024-05-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_disponibiliteconseiller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisponibiliteConseiller',
        ),
    ]
