# Generated by Django 4.1.13 on 2024-05-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_delete_disponibiliteconseiller'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibiliteConseiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.conseiller')),
            ],
            options={
                'db_table': 'DisponibiliteConseillers',
            },
        ),
    ]
