# Generated by Django 4.1.13 on 2024-05-17 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_disponibiliteconseiller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibiliteconseiller',
            name='date',
        ),
        migrations.RemoveField(
            model_name='disponibiliteconseiller',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='disponibiliteconseiller',
            name='heure_fin',
        ),
        migrations.AddField(
            model_name='demande',
            name='date_heure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='disponibiliteconseiller',
            name='date_heure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
