# Generated by Django 4.1.13 on 2024-05-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_disponibiliteconseiller_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='CIN',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='CNE',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
