# Generated by Django 4.1.13 on 2024-05-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_etudiant_cin_alter_etudiant_cne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='CIN',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='CNE',
        ),
    ]
