# Generated by Django 4.1.13 on 2024-05-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_remove_etudiant_cin_remove_etudiant_cne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandes', models.ManyToManyField(blank=True, to='website.demande')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.etudiant')),
                ('feedbacks', models.ManyToManyField(blank=True, to='website.feedback')),
            ],
            options={
                'db_table': 'Dossiers',
            },
        ),
    ]
