# Generated by Django 4.1.13 on 2024-05-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_dossier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dossier',
        ),
    ]
