# Generated by Django 4.1.13 on 2024-05-20 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_delete_dossier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.etudiant')),
            ],
            options={
                'db_table': 'Dossiers',
            },
        ),
    ]
