# Generated by Django 4.1.13 on 2024-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='demandes',
            field=models.ManyToManyField(blank=True, to='website.demande'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='feedbacks',
            field=models.ManyToManyField(blank=True, to='website.feedback'),
        ),
    ]
