# Generated by Django 4.1.13 on 2024-05-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseiller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
