# Generated by Django 4.1.13 on 2024-05-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_conseiller_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseiller',
            name='est_connecte',
            field=models.BooleanField(default=False),
        ),
    ]
