# Generated by Django 4.1.13 on 2024-05-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
