# Generated by Django 4.1.13 on 2024-05-29 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_etudiant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_ajout_feedback',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
