# Generated by Django 4.1.13 on 2024-05-30 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_feedback_date_ajout_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='date_ajout_dossier',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
