# Generated by Django 4.1.13 on 2024-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_alter_dossier_date_ajout_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='date_ajout_dossier',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
