# Generated by Django 4.1.13 on 2024-05-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_alter_dossier_date_ajout_dossier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomComplet', models.CharField(max_length=255)),
                ('EmailAuteur', models.EmailField(max_length=254)),
                ('Question', models.TextField()),
                ('Reponse', models.TextField(blank=True, null=True)),
                ('dateAjoutDeQuestion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
    ]
