# Generated by Django 4.1.13 on 2024-06-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='conseiller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.conseiller'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.etudiant'),
        ),
    ]
