# Generated by Django 4.1.13 on 2024-06-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_alter_feedback_conseiller_alter_feedback_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Quotes',
            },
        ),
    ]
