# Generated by Django 4.1.13 on 2024-06-03 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TODO', models.CharField(max_length=255)),
                ('DateAjoutTODO', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignee_conseiller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.conseiller')),
                ('assignee_etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.etudiant')),
            ],
            options={
                'db_table': 'TODOs',
            },
        ),
    ]
