# Generated by Django 4.1.13 on 2024-06-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('visiteur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.visiteur')),
                ('collaboration', models.TextField()),
            ],
            options={
                'db_table': 'Collaborateurs',
            },
            bases=('website.visiteur',),
        ),
    ]
