# Generated by Django 4.1.13 on 2024-06-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_collaborateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collaborateur',
        ),
    ]
