# Generated by Django 4.1.13 on 2024-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_delete_collaborateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('collaboration', models.TextField()),
            ],
            options={
                'db_table': 'Collaborateurs',
            },
        ),
    ]
