# Generated by Django 4.1.13 on 2024-06-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_collaborateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='etat',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('upcoming', 'Upcoming')], default='upcoming', max_length=10),
        ),
    ]
