# Generated by Django 4.1.13 on 2024-06-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_event_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='etudiants',
            field=models.ManyToManyField(related_name='events', to='website.etudiant'),
        ),
    ]
