# Generated by Django 4.1.13 on 2024-06-07 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_event_etudiants'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='dateJoining',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='dateJoining',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conseiller',
            name='dateJoining',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='dateJoining',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visiteur',
            name='dateJoining',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
