# Generated by Django 4.1.13 on 2024-06-09 10:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_administrateur_datejoining_collaborateur_datejoining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('date_observation', models.DateTimeField(default=django.utils.timezone.now)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='website.demande')),
            ],
            options={
                'db_table': 'Observations',
            },
        ),
    ]
