# Generated by Django 4.1.13 on 2024-06-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_ressource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='description',
            field=models.TextField(),
        ),
    ]
