# Generated by Django 4.1.13 on 2024-06-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_alter_ressource_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='dateAjoutRessource',
            field=models.DateField(),
        ),
    ]
