# Generated by Django 4.1.13 on 2024-06-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_alter_ressource_dateajoutressource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborateur',
            old_name='Nom',
            new_name='entreprise_associee',
        ),
        migrations.RenameField(
            model_name='collaborateur',
            old_name='Prenom',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='collaborateur',
            old_name='motDePasse',
            new_name='poste_occupe',
        ),
        migrations.RenameField(
            model_name='collaborateur',
            old_name='nomUtilisateur',
            new_name='prenom',
        ),
        migrations.RenameField(
            model_name='collaborateur',
            old_name='phoneNumber',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='collaboration',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='dateJoining',
        ),
    ]
