# Generated by Django 4.1.13 on 2024-06-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_rename_nom_collaborateur_entreprise_associee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='conseiller',
        ),
    ]
